[package]
name = "prancing_pony"
version = "0.1.0"
edition = "2021"
description = "Simple implementation of Knight's tour using backtrack"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
